// alert("HELLO!!!!!!!!!!!!!!!!!!!!");
// console.log("first program"); 
console.log("5");
let x;
x=10;
console.log(x);
x=20;
console.log(x);
x="myword";
console.log(x);
let y=30, z,y1=31;
console.log(y,z, y1);



//1.case senstive
let year=1000;
// console.log(Year);this will throw  an error as js is the case sentive language as y of year capital this is completely different variable
console.log(year);


//2.No sepical charactere except _(underscore) and $(dollar symbole)
let nam1="rohit";
let rohit$balance=770;
let my_age=27;
//cann't use  @,#,%other symbole in naming a variable

console.log(nam1);
console.log(rohit$balance);
console.log(my_age);
//cannot start from number,no used of reserved keyword, no space